### PR TITLE
Add fallback source type to handle errors

### PR DESCRIPTION
**Pull request by tbonfort**
In the same vein as fallback caches, this PR adds support for fallback sources. If the first configured source fails, mapcache will cycle the remaining configured sources until/if one succeeds. If all fail, the error message of the first failing source will be returned.

example usage/config:
```
<source name="wms1" type="wms">
 <!-- wms 1 config opts -->
</source>

<source name="wms2" type="wms">
 <!-- wms 2 config opts. Most probably the same as for wms except for the server hostname, unless you know what you are doing -->
</source>

<source name="fallbackwms" type="fallback">
 <source>wms1</source>
 <source>wms2</source>
</source>

<tileset name="foo">
 <source>fallbackwms</source>
 <!-- ... -->
</tileset>
```

### CODE REVIEW

**Comment by tbonfort** [comment]
cc @tevbrasch

**Comment by jbo-ads** [comment]
@tbonfort - Is this pull request still relevant?

**Comment by tbonfort** [comment]
@tevbrasch are you still using this? If so please create a new PR based against the current main branch so it can be included.

**Comment by tevbrasch** [comment]
Hi @tbonfort , yes we're still using this. But we haven't made a any additions or changes, so not sure why it needs a new PR?

**Comment by jmckenna** [comment]
Thanks @tevbrasch , this does look like it would be very useful to the community, and it was already re-based to the main branch automatically.  We should re-open this ticket and set the target to the upcoming 1.12.0 release.  For some reason I am unable to re-open here, can someone else re-open this ticket?

**Comment by tbonfort** [comment]
> Hi @tbonfort , yes we're still using this. But we haven't made a any additions or changes, so not sure why it needs a new PR?

@tevbrasch for this to be included in an upcoming release, someone has to take the time and effort to fix the merge conflicts. Once that's done the result can be pushed to a new PR and be milestoned.

**Comment by jmckenna** [comment]
@tevbrasch I don't have a local copy of these changes, as unfortunately the directory with the changes was just deleted.  Would you mind filing a new pull request with those changed files?  thanks.

**Pull request closed without merging**
