### PR TITLE
Add support for pcre2.

### PR DESCRIPTION
**Pull request by sebastic**
This is my naive attempt to add support for [PCRE2](http://pcre.org/current/doc/html/).

It builds successfully, but my C-fu is not very strong, so I'm not sure about the correctness.

@jmckenna can you review this?

### CODE REVIEW

**Comment by jmckenna** [comment]
thanks @sebastic I'll test this...

**Comment by jmckenna** [comment]
Thanks @sebastic works very well on Windows!  (I also made some other minor changes to CMakeLists.txt in this PR to remove some warnings)  I think we should merge this.

**Comment by sebastic** [comment]
> I think we should merge this

Maybe rebase it first to not have such an ugly history?

**Comment by jmckenna** [comment]
ok I will try "rebase and merge" (I was initially going to "squash and merge" & remove my history)

**Pull request merged**
