### PR TITLE
Insert #include <unistd.h> in mapcache_detail.c

### PR DESCRIPTION
**Pull request by jbo-ads**
This pull request aims at solving issue #200.

### CODE REVIEW

**Comment by geographika** [comment]
For win32 would adding in io.h or windows.h work here?

https://stackoverflow.com/a/1759731/179520

**Comment by jbo-ads** [comment]
Yes, I will check that as soon as I reach a Windows machine. AppVeyor didn’t complain because it includes OGR/GEOS packages.

**Comment by mcoudert** [comment]
Thanks Jérôme for having solved that! 
As you adviced me, I managed to compile deactivating the contrib (-DWITH_MAPCACHE_DETAIL=0).

**Comment by jbo-ads** [comment]
I checked whether <io.h> or <windows.h> should be added on Windows platform to replace <unistd.h> : actually neither is needed in that specific case. `mapcache_detail.exe` compiles and executes fine with code from  commit 0b85571.

**Comment by geographika** [comment]
@jbo-ads - are you happy for this to be merged now?

**Comment by jbo-ads** [comment]
Sorry for late answer. Yes this can safely be merged.

**Pull request merged**
