### PR TITLE
watermark on request

### PR DESCRIPTION
**Pull request by ruester**
The current watermark option always merges the watermarkfile on top of the tiles and then saves the watermarked tile in the cache.
I've added a option which still let you see a watermark on requested tiles, but which will not be saved watermarked to the cache.

To get this behaviour you have to add following to the configuration file:

``` xml
<tileset name="test">
    <watermark onrequest="true">/path/to/file</watermark>
</tileset>
```

### CODE REVIEW

**Comment by jbo-ads** [comment]
@ruester - Is this pull request still relevant?

**Comment by ruester** [comment]
As this PR is very old and was not merged till now, we can close it... If someone needs this feature they can use these commits to implement it for a newer version of mapcache 👍

**Comment by jmckenna** [comment]
@ruester we're doing a push for the upcoming 1.12.0 release and these changes could be included.  Please re-open this as it is a good enhancement for the community.

**Comment by ruester** [comment]
Oh ok, sure you can add this, but I will have no time for rebasing the commits or fix the implementation if needed..

**Comment by jmckenna** [comment]
ok thanks for explaining. Closing.

**Pull request closed without merging**
