### PR TITLE
create world files

### PR DESCRIPTION
**Pull request by ruester**
When caching to disk or tiff it is useful to also create world files for the images.
So we are able to generate all tiles using mapcache_seed and then use the same raster data for a WMS service.

To use this feature following has to be added to the configuration file:

``` xml
<cache ...>
    <create_world_file/>
</cache>
```

We used the file extension ".wld" for the world files as suggested by MapServer ([see here](http://mapserver.org/de/input/raster.html#georeference-with-world-files)).

### CODE REVIEW

**Comment by jbo-ads** [comment]
@ruester - Is this pull request still relevant?

**Comment by ruester** [comment]
As this PR is very old and was not merged till now, we can close it... If someone needs this feature they can use these commits to implement it for a newer version of mapcache 👍

**Comment by jmckenna** [comment]
@ruester we're doing a push for the upcoming 1.12.0 release and these changes could be included.  Please re-open this as it is a good enhancement for the community.

**Comment by ruester** [comment]
Oh ok, sure you can add this, but I will have no time for rebasing the commits or fix the implementation if needed..

**Comment by jmckenna** [comment]
ok thanks for explaining. Closing.

**Pull request closed without merging**
