### PR TITLE
Fix MSVC build

### PR DESCRIPTION
**Pull request by jmckenna**
this tackles the following issues with builds on Windows with Visual Studio:

 - C89 requirement of declaring variables at beginning of the block
 - DLL exports in the library (issue #110)
 - workaround for timegm (issue #112)
 - cmake's finding of PNG libraries (issue #111)

### CODE REVIEW

**Comment by sdlime** [comment]
Changes seem ok, do you want to wait for @tbonfort or merge this yourself? --Steve

**Comment by jmckenna** [comment]
Thanks for reviewing Steve. I wondered the same yesterday.  Will merge myself, I am sure Thomas can fix any mistakes later.  -jeff

**Comment by tbonfort** [comment]
thanks @jmckenna !

**Comment by tbonfort** [comment]
in 219e54b45e4730 I have added a check that prevents code not respecting C89-style variable declarations to compile, so that this issue hopefully doesn't need to be gone over again.

**Comment by jmckenna** [comment]
ah great, I see it in  CMakeLists.txt now.  Thanks @tbonfort !

**Pull request merged**
