### PR TITLE
Improved seeding logging

### PR DESCRIPTION
**Pull request by rnijveld**
When running mapcache_seed on kubernetes we've noticed two things that make working with mapcache_seed somewhat frustrating. 

Firstly mapcache_seed doesn't output anything while it is skipping tiles. This means that it might take a long time before we get any output at all on partially seeded tilesets. I've added some code such that when a tile is skipped, a skip message is sent to the logging task and the output is amended to include a number of skipped tiles.

The second issue we've run into is that progress is always printed on a single line that was being overwritten. This causes some issues with logging in kubernetes, as it expects logging to be done a single new line after another. I've added a flag (now called `-non-interactive` or `-b`) that switches the behavior of the progress messages, such that each progress message is printed on a new line. I'm sure a better name for such a flag exists, but I'm unsure what to call it.

I'm unsure if this is something that should be in mapcache_seed by default, but I'd love to get your feedback.

### CODE REVIEW

**Comment by jbo-ads** [comment]
Improving logs is a good idea. I have no opinion about the flag name. But I wonder whether "_skipped_" is a good choice for tiles that don't need to be seeded. It might includes tiles skipped for other reasons (server error for instance). May I suggest something like "_already in cache_"?

**Comment by rnijveld** [comment]
I've currently used the same terminology as was used internally. For 'already in cache', should we also change the message when we're running in delete mode, because then the meaning of the skipping action would be reversed I think? 

When `MAPCACHE_CMD_SKIP` is returned from `examine_tile`, is it always because of not existing/existing in the target cache? I wasn't sure, which is why I chose to stick to 'skipped'.

**Comment by jbo-ads** [comment]
You are right, I forgot about delete mode. "_skipped_" has the advantage of being versatile.

**Comment by jbo-ads** [comment]
It would be great if you could update the documentation [MapCache Seeder](https://mapserver.org/mapcache/seed.html).

**Pull request merged**
