### PR TITLE
Redis cache backend

### PR DESCRIPTION
**Pull request by etscrivner**
This pull request adds [Redis](http://redis.io) as an optional cache backend.

**Explanation:**

The organization I work for ([ParkMe](http://parkme.com)) currently uses the mapserver with the memcached backend to render parking location information. Recent updates to our infrastructure have led to a roadmap in which we phase out memcached in favor of [redis](http://redis.io). This is a provisional take at implementing a mapserver cache backend for redis that is production-ready.

### CODE REVIEW

**Comment by tbonfort** [comment]
my etscrivner-add-redis-cache branch contains an updated version of this PR with support for the connection pooling that was introduced in branch-1-4, along with some minor fixups. Please give it a try and report back so we can add this to the next release.

**Comment by tbonfort** [comment]
@etscrivner any chance you're going to be able to test this?

**Comment by etscrivner** [comment]
@tbonfort I thoroughly tested the previous version (without connection pooling) on our production system. If you'd like I can do the same with the connection-pooled version as I have time? I'd probably get to it next week some time.

**Comment by tbonfort** [comment]
@etscrivner that would be great. I'll merge into master once you give the go, no hurry though

**Comment by pcallewaert** [comment]
this looks like a great feature, any update on this?

**Comment by tablet-mode** [comment]
I'm interested in this feature as well. Is there anything specific holding it back?

**Comment by etscrivner** [comment]
@pcallewaert @tablet-mode 
I haven't worked on this in a couple of years and don't plan to. It looks like there's some pending connection pooling code as well as merge conflicts.

If either of you are willing to fix those and re-test could probably get this off the ground fairly quickly.

**Comment by jbo-ads** [comment]
@etscrivner, @tbonfort, @sdlime, @pcallewaert, @t4k1t,  Anyone willing to work on this?

**Comment by t4k1t** [comment]
> 
> 
> @etscrivner, @tbonfort, @sdlime, @pcallewaert, @t4k1t, Anyone willing to work on this?

I'm afraid not. I haven't been with the company interested in this for a few years now.

**Pull request merged**
